version: '3'
services:
   app:
      container_name: app
      restart: always
      build: .
      working_dir: /usr/src/app
      ports:
         - '5000:5000'
      external_links:
         - mongo
   mongo:
      container_name: mongo
      image: mongo
      ports:
         - '27017:27017'
